apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.application }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.application }}
  template:
    metadata:
      labels:
        app: {{ .Values.application }}
    spec:
      containers:
        - name: {{ .Values.application }}
          image: {{ .Values.werf.image.app }}
      imagePullSecrets:
        - name: dockerconfigjson-github-com