---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.application }}
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`{{ .Values.domain }}`)
    kind: Rule
    services:
    - name: {{ .Values.application }}
      port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.application }}-tls
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{ .Values.domain }}`)
    kind: Rule
    services:
    - name: {{ .Values.application }}
      port: 80
  tls:
    certResolver: letsencrypt
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.application }}-redirect-to-https
spec:
  redirectScheme:
    scheme: https
    permanent: true